# Generated by Django 4.2.1 on 2023-06-16 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datphong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgdat', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ttkhach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdt', models.CharField(max_length=11, null=True)),
                ('ngaydat', models.DateTimeField(auto_now_add=True)),
                ('datphong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.datphong')),
                ('nguoidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='dsdat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(default=0, null=True)),
                ('ngaydat', models.DateTimeField(auto_now_add=True)),
                ('datphong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.datphong')),
                ('phong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
        ),
        migrations.AddField(
            model_name='datphong',
            name='nguoidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nguoidung'),
        ),
    ]
