# Generated by Django 4.2.1 on 2023-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
