# Generated by Django 4.2.1 on 2023-06-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_phong_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datphong',
            old_name='nguoidat',
            new_name='nd',
        ),
    ]
